# Generated by Django 3.2.7 on 2021-09-08 17:25

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=20)),
                ('lastname', models.TextField(max_length=20)),
                ('password', models.TextField(max_length=20)),
                ('email', models.TextField(max_length=35)),
                ('phone', models.TextField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.upload_path)),
            ],
        ),
    ]
