# Generated by Django 3.2.7 on 2021-09-24 15:44

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_friendlist_friendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to=api.models.upload_path_jobs)),
                ('participants', models.ManyToManyField(blank=True, related_name='participants_list', to='api.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
