# Generated by Django 3.2.7 on 2021-09-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_job_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date',
        ),
    ]
