# Generated by Django 3.2.7 on 2021-09-26 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_job_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidates', models.ManyToManyField(blank=True, related_name='candidates', to='api.Job')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='api.job')),
            ],
        ),
    ]
