# Generated by Django 3.2.7 on 2021-09-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_participantslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantslist',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='candidates', to='api.UserProfile'),
        ),
    ]
