# Generated by Django 3.2.7 on 2021-09-27 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_personaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_1', to='api.userprofile')),
                ('member_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_2', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=400)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user', to='api.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MessageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='api.conversation')),
                ('messages', models.ManyToManyField(blank=True, related_name='messages', to='api.Message')),
            ],
        ),
    ]
