# Generated by Django 3.2.7 on 2021-09-30 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receiver_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_note', to='api.userprofile')),
                ('sender_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_note', to='api.userprofile')),
            ],
        ),
    ]
